spring:
  docker:
    compose:
      enabled: false
  application:
    name: chocolateria

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only

  metrics:
    tags:
      application: chocolateria
      environment: dev
