spring:
  docker:
    compose:
      enabled: false
  application:
    name: chocolateria

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: chocolateria